### PR TITLE
0.3.0 RC

### LINKED ISSUE #7: Transaction.GetOutput (txId, vout)
@jprichardson @weilu thoughts on this new end point?
Suggested by @sidazhang for use in block-explorer like pages to avoid multiple API calls and tedious transaction parsing. 

I'm not sure.

``` javascript
[
  {
    txId: "c7736a0a0046d5a8cc61c8c3c2821d4d7517f5de2bc66a966011aaa79965ffba",
    scriptPubKey: "61b469ada61f37c620010912a9d5d56646015f16",
    value: 10505,
    vout: 0
  },
  ...
]
```

### PR DESCRIPTION
**Pull request by dcousens**
This pull request migrates the API to `0.3.0`.

It resolves #7, #8 and #9.

It also attempts to improve the API by introducing more idem-potency across the API, with various notes introduced where subjectivity [that is, return results] could vary between nodes. 

This is obviously a breaking change with `0.2.0`,  but I think that is well understood.

### CODE REVIEW

**Comment by jprichardson** [comment]
Looks good. A couple of questions:

1. In https://github.com/common-blockchain/common-blockchain/commit/14f2872ec87ec33f4e7a3db5236f9561391da7db, why include `blockHex` and `txHex`? Feels a bit heavyweight, especially `blockHex`.
2. In https://github.com/common-blockchain/common-blockchain/commit/d820076ab0fc5599fd2f0e9a3bc2c7b5a8a3fe19, why a single tx hex now and not an array? Presumably simplification? Whatever the case, I like it.

**Comment by dcousens** [comment]
@jprichardson

1. I'm not seeing what you're referring to?  Can you comment inline?
2. See closing comments on https://github.com/common-blockchain/common-blockchain/issues/8

**Comment by jprichardson** [comment]
1. LOL, never mind. I was too fixated on a previous discussion that included `blockHex` and I immediately thought of that without considering the context. My fault.
2. Makes perfect sense.

**Comment by dcousens** [comment]
Want to move quicker on this,  happy to discuss any of the changes at any step as we go forward.

**Pull request merged**
