### PR TITLE
0.4.0 RC - Minimize data duplication in endpoints

### PR DESCRIPTION
**Pull request by dcousens**
This PR removes all data duplication throughout the API, leaving end points to be specific to their purpose, with no convenience data returned.

This means the entire API is more focused, and less prone to 'convenience' creep.

The reason I feel this is necessary, is due to the fact that convenience is highly use case dependent.

Often, if an implementation expands beyond the original use case, these parts of the API begin to become large data sinks which contain superfluous data you may already have.

### CODE REVIEW

**Comment by rubensayshi** [comment]
from out chat:

- [x] Addresses.Transactions should be filtered by blockId, this would also allow use to return an error if thet blockId is orphaned
- [ ] I'm a big fan of including blockId or blockHeight in Transactions.Get too
- [x] Blocks.Get needs to have blockHeight too (it's no in the blockHex)
- [ ] maybe Blocks.Latest should have the blockHeight too ... not sure
- [ ] Transactions.Propegate should specify it's return value better (either `{}` or `null` or `txId`)

**Comment by dcousens** [comment]
For the filter.  I think instead it might be best applied to
Block.Transactions instead.   With the filter on Addresses.Transactions
removed entirely.   I say this because at the moment it is a range filter,
and we are suggesting changing it to be a filter based on the given block
id.   In that sense,  it might make more sense to do the reverse.

This might also mean the following API would be beneficial:

Blocks.Since

Which, given a block id, would either give the list of blocks since, or
error if orphaned.

Then,  to update your cache,   you would just get blocks since last
update,   then do. Blocks.Transactions for those blocks.

This is naturally closer to an SPV client,  but,  it doesn't hinder on any
aspect of the current API no?

Overall I think this needs more thought,  but I think we're getting closer
to building an API that can be more verifiable and less subjective,  as
well as maintaining a minimal foot print.

**Comment by dcousens** [comment]
> Transactions.Propegate should specify it's return value better (either `{}` or `null` or `txId`)

As discussed, this isn't really necessary.  No response body is perfectly valid too, its essentially `null` at a different level.

If the API is implemented using JSend for example, you could just return `null`, but you can't return undefined.  As long as the user understands that there is no expected return value in the valid case.

**Comment by jprichardson** [comment]
Why not just return the `txId`?

On Tue, Apr 7, 2015 at 9:55 PM, Daniel Cousens <notifications@github.com>
wrote:

> Transactions.Propegate should specify it's return value better (either {}
> or null or txId)
>
> As discussed, this isn't really necessary. No response body is perfectly
> valid too, its essentially null at a different level.
>
> If the API is implemented using JSend for example, you could just return
> null, but you can't return undefined. As long as the user understands
> that there is no expected return value in the valid case.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/common-blockchain/common-blockchain/pull/18#issuecomment-90789127>
> .
>



-- 
Simple & Secure Bitcoin Wallet: https://www.coinbolt.com
Bitcoin / JavaScript: http://cryptocoinjs.com
Follow JP Richardson on Twitter: https://twitter.com/jprichardson

**Comment by dcousens** [comment]
As discussed in the chat, because it doesn't make sense to given the user already has that information.  What usefulness does it convey?

``` javascript
var txId = tx.getId(),
var txHex = tx.toHex()

bc.transactions.propagate(txHex, function(err, txId2) {
  if (err) throw err
  // do I compare txId and txId2?  Why do I have this, are they different? What?
})
```

**Comment by dcousens** [comment]
Hoping to merge today and start porting the changes to https://github.com/dcousens/cb-tester. 

Then hopefully we can roll these changes out quickly to the https://github.com/common-blockchain/cb-node module.

**Comment by rubensayshi** [comment]
if I would be the designer, implementator and consumer of the API my code with 100% for sure look like: 
```
var txId = tx.getId(),
var txHex = tx.toHex()

bc.transactions.propagate(txHex, function(err, txId2) {
  if (err) throw err
  if (txId2 !== txId) throw new Error("Something odd");
})
```

just to give me a little ease of mind I guess that everything went well ...

**Comment by dcousens** [comment]
I guess that is the default behavior for bitcoind...

**Comment by dcousens** [comment]
Returning `txId` is not an indication that everything went 'OK'.
There is no way to prove that except to cross reference it against other nodes.

**Pull request closed without merging**
